
[package]
name = "game_dylib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
Final_project = { path = "../game", default-features = false }

[features]
default = ["Final_project/default"]
dylib-engine = ["Final_project/dylib-engine"]
